import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ThemeToggle } from "@/components/ThemeToggle";
import { lovable } from "@/integrations/lovable";
import { supabase } from "@/integrations/supabase/client";

const LEGAL_VERSION = "2026-08-21";
export const Route = createFileRoute("/auth")({ head:()=>({meta:[{title:"Entrar | Finance Flow AI"},{name:"description",content:"Aceda à sua conta Finance Flow AI."}]}), validateSearch:(search:Record<string,unknown>)=>({modo:search["modo"]==="registo"?("registo" as const):("entrar" as const)}), component:AuthPage });
function friendlyOAuthError(raw:string,provider:"google"|"apple"){const l=raw.toLowerCase();if(l.includes("missing oauth secret")||l.includes("unsupported provider")||l.includes("provider is not enabled"))return provider==="google"?"O login com Google ainda não está ativado no servidor.":"O login com Apple ainda não está ativado no servidor.";if(l.includes("redirect"))return "URL de redirecionamento não autorizada.";return raw||"Não foi possível continuar com o login social."}
function AuthPage(){const {modo}=Route.useSearch();const navigate=useNavigate();const [mode,setMode]=useState<"entrar"|"registo">(modo);const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [loading,setLoading]=useState(false);const [oauthLoading,setOauthLoading]=useState<"google"|"apple"|null>(null);const [accepted,setAccepted]=useState(false);
 async function handleOAuth(provider:"google"|"apple"){if(!accepted){toast.error("Aceite os Termos de Utilização e a Política de Privacidade para continuar.");return}setOauthLoading(provider);try{const redirectTo=`${window.location.origin}/painel`;const {data,error}=await supabase.auth.signInWithOAuth({provider,options:{redirectTo,skipBrowserRedirect:true}});if(!error&&data?.url){window.location.assign(data.url);return}const lovableResult=await lovable.auth.signInWithOAuth(provider,{redirect_uri:redirectTo});if(lovableResult.redirected)return;if(lovableResult.error){const msg=lovableResult.error instanceof Error?lovableResult.error.message:String(lovableResult.error);toast.error(friendlyOAuthError(error?.message||msg,provider));return}void navigate({to:"/painel",replace:true})}catch(error){toast.error(friendlyOAuthError((error as Error).message??"Não foi possível continuar.",provider))}finally{setOauthLoading(null)}}
 async function handleForgotPassword(){if(!email){toast.error("Escreva primeiro o seu e-mail.");return}const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/redefinir-senha`});if(error)toast.error(error.message);else toast.success("Enviámos-lhe um e-mail para redefinir a palavra-passe.")}
 useEffect(()=>{const params=new URLSearchParams(window.location.search);const err=params.get("error_description")||params.get("error");if(err){toast.error(friendlyOAuthError(decodeURIComponent(err),"google"));window.history.replaceState({},"",window.location.pathname)}supabase.auth.getSession().then(({data})=>{if(data.session)void navigate({to:"/painel",replace:true})})},[navigate]);
 async function handleSubmit(e:React.FormEvent){e.preventDefault();if(!accepted){toast.error("Aceite os Termos de Utilização e a Política de Privacidade para continuar.");return}setLoading(true);try{if(mode==="registo"){const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:`${window.location.origin}/painel`,data:{legal_consent:true,legal_consent_version:LEGAL_VERSION,legal_consent_at:new Date().toISOString()}}});if(error)throw error;if(data.session)void navigate({to:"/painel",replace:true});else toast.success("Conta criada. Confirme o e-mail que lhe enviámos para entrar.")}else{const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;if(data.user?.user_metadata?.["legal_consent"]!==true||data.user.user_metadata?.["legal_consent_version"]!==LEGAL_VERSION){const {error:updateError}=await supabase.auth.updateUser({data:{legal_consent:true,legal_consent_version:LEGAL_VERSION,legal_consent_at:new Date().toISOString()}});if(updateError)throw updateError}void navigate({to:"/painel",replace:true})}}catch(error){toast.error((error as Error).message??"Não foi possível continuar.")}finally{setLoading(false)}}
 return <main className="relative flex min-h-screen items-center justify-center px-5 py-14"><div className="absolute right-5 top-5"><ThemeToggle/></div><div className="panel panel-crown w-full max-w-md p-8 animate-fade-up"><p className="eyebrow">Finance Flow AI</p><h1 className="mt-2 font-display text-2xl font-bold tracking-tight">{mode==="registo"?"Criar conta":"Entrar na conta"}</h1><p className="mt-2 text-sm text-muted-foreground">A mesma conta dá acesso aos mesmos dados no PC e no iPhone.</p>
 <Button type="button" variant="outline" className="mt-7 w-full gap-2" disabled={oauthLoading!==null} onClick={()=>handleOAuth("google")}>{oauthLoading==="google"?"A abrir o Google…":"Continuar com Google"}</Button><Button type="button" variant="outline" className="mt-3 w-full gap-2" disabled={oauthLoading!==null} onClick={()=>handleOAuth("apple")}>{oauthLoading==="apple"?"A abrir a Apple…":"Continuar com Apple"}</Button>
 <div className="my-6 flex items-center gap-3 text-xs text-muted-foreground"><span className="h-px flex-1 bg-border"/>ou com e-mail<span className="h-px flex-1 bg-border"/></div><form className="grid gap-4" onSubmit={handleSubmit}><div className="grid gap-1.5"><Label htmlFor="email">E-mail</Label><Input id="email" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></div><div className="grid gap-1.5"><div className="flex items-center justify-between"><Label htmlFor="password">Palavra-passe</Label>{mode==="entrar"&&<button type="button" className="text-xs text-muted-foreground underline-offset-4 hover:underline" onClick={handleForgotPassword}>Esqueci-me</button>}</div><Input id="password" type="password" autoComplete={mode==="registo"?"new-password":"current-password"} minLength={6} required value={password} onChange={e=>setPassword(e.target.value)}/></div>
 <label className="flex items-start gap-3 rounded-xl border bg-muted/20 p-3 text-xs leading-5"><input type="checkbox" className="mt-1 size-4" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>Li e aceito os <Link to="/termos-de-utilizacao" target="_blank" className="font-semibold underline">Termos de Utilização</Link> e a <Link to="/politica-de-privacidade" target="_blank" className="font-semibold underline">Política de Privacidade</Link>. O acesso à plataforma só é permitido após este consentimento.</span></label>
 <Button type="submit" disabled={loading||!accepted} className="mt-1">{loading?"Aguarde…":mode==="registo"?"Criar conta":"Entrar"}</Button></form><button type="button" className="mt-6 w-full text-sm text-muted-foreground underline-offset-4 hover:underline" onClick={()=>setMode(mode==="registo"?"entrar":"registo")}>{mode==="registo"?"Já tenho conta — entrar":"Ainda não tenho conta — criar agora"}</button></div></main>}
