import { AlertTriangle, CalendarClock, Gauge, TrendingUp, Users } from "lucide-react";
import { useMemo } from "react";
import type { Entry, Settings } from "@/lib/finance";

const fmt = (n:number,c:string)=>new Intl.NumberFormat("pt-PT",{style:"currency",currency:c,maximumFractionDigits:0}).format(Number.isFinite(n)?n:0);
const monthKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;

export function BusinessOverviewPro({entries,settings}:{entries:Entry[];settings:Settings|null}){
 const currency=settings?.currency??"EUR";
 const data=useMemo(()=>{
  const now=new Date();
  const months=Array.from({length:6},(_,i)=>{const d=new Date(now.getFullYear(),now.getMonth()-i,1);const key=monthKey(d);const rows=entries.filter(e=>e.entry_date.slice(0,7)===key);const income=rows.filter(e=>e.type==="income").reduce((s,e)=>s+Number(e.value||0),0);const expense=rows.filter(e=>e.type==="expense").reduce((s,e)=>s+Number(e.value||0),0);return{key,income,expense,balance:income-expense}});
  const current=months[0],previous=months[1];const completed=months.slice(1).filter(m=>m.income||m.expense);const avgIncome=completed.length?completed.reduce((s,m)=>s+m.income,0)/completed.length:current.income;const avgExpense=completed.length?completed.reduce((s,m)=>s+m.expense,0)/completed.length:current.expense;const avgProfit=avgIncome-avgExpense;
  const totalIncome=entries.filter(e=>e.type==="income").reduce((s,e)=>s+Number(e.value||0),0);const totalExpense=entries.filter(e=>e.type==="expense").reduce((s,e)=>s+Number(e.value||0),0);const cash=totalIncome-totalExpense;const runway=avgExpense>0?Math.max(0,cash/avgExpense):0;
  const clients=new Map<string,{revenue:number,visits:number}>();for(const e of entries.filter(e=>e.type==="income")){const name=(e.client||"").trim();if(!name)continue;const x=clients.get(name)??{revenue:0,visits:0};x.revenue+=Number(e.value||0);x.visits+=1;clients.set(name,x)}
  const repeat=clients.size?[...clients.values()].filter(c=>c.visits>=2).length/clients.size:0;const growth=previous.income>0?(current.income-previous.income)/previous.income:0;const margin=current.income>0?current.balance/current.income:0;let score=50;if(avgProfit>0)score+=15;else score-=15;if(runway>=3)score+=10;else if(runway<1)score-=10;if(repeat>=.35)score+=10;if(growth>.1)score+=10;else if(growth<-.15)score-=10;if(margin>=.2)score+=5;score=Math.max(0,Math.min(100,Math.round(score)));
  const notes:string[]=[];if(avgProfit<0)notes.push("A média recente está negativa: reveja custos e preços.");if(runway<2&&avgExpense>0)notes.push(`O caixa cobre cerca de ${runway.toFixed(1)} meses da despesa média.`);if(repeat<.25&&clients.size>=5)notes.push("A recorrência de clientes está baixa; follow-up pode ajudar a aumentar retorno.");if(growth>.1)notes.push(`A receita cresceu ${Math.round(growth*100)}% face ao mês anterior.`);if(!notes.length)notes.push("Os indicadores principais estão equilibrados neste momento.");
  return{score,avgIncome,avgExpense,avgProfit,cash,runway,forecast30:cash+avgProfit,forecast90:cash+avgProfit*3,repeat,growth,margin,clients:clients.size,notes:notes.slice(0,3)};
 },[entries]);
 return <section className="panel panel-crown p-5 lg:p-6 animate-fade-up"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="eyebrow">Business Command Center</p><h2 className="mt-1 font-display text-lg font-semibold">Visão executiva do negócio</h2><p className="mt-1 text-xs text-muted-foreground">Caixa, projeção, margem e clientes numa leitura rápida.</p></div><div className="rounded-2xl border bg-background/60 px-4 py-3 text-right"><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Business Score</p><p className="text-2xl font-bold">{data.score}<span className="text-sm text-muted-foreground">/100</span></p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card icon={CalendarClock} label="Caixa projetado 30d" value={fmt(data.forecast30,currency)} hint={`90d: ${fmt(data.forecast90,currency)}`}/><Card icon={Gauge} label="Fôlego de caixa" value={`${data.runway.toFixed(1)} meses`} hint={`Despesa média ${fmt(data.avgExpense,currency)}/mês`}/><Card icon={TrendingUp} label="Margem do mês" value={`${Math.round(data.margin*100)}%`} hint={data.growth?`${data.growth>0?"+":""}${Math.round(data.growth*100)}% receita vs. mês anterior`:"Sem base anterior suficiente"}/><Card icon={Users} label="Clientes recorrentes" value={`${Math.round(data.repeat*100)}%`} hint={`${data.clients} clientes identificados`}/></div><div className="mt-4 rounded-2xl border bg-background/45 p-4"><div className="flex items-center gap-2"><AlertTriangle className="size-4 text-primary"/><h3 className="text-sm font-semibold">Leitura inteligente</h3></div><ul className="mt-3 space-y-2 text-sm text-muted-foreground">{data.notes.map(n=><li key={n}>• {n}</li>)}</ul></div></section>
}
function Card({icon:Icon,label,value,hint}:{icon:React.ComponentType<{className?:string}>;label:string;value:string;hint:string}){return <div className="rounded-2xl border bg-background/50 p-4"><div className="flex items-center gap-2 text-muted-foreground"><Icon className="size-4"/><span className="text-xs font-medium">{label}</span></div><p className="mt-2 text-xl font-bold tracking-tight">{value}</p><p className="mt-1 text-[11px] text-muted-foreground">{hint}</p></div>}
