import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Clipboard, Megaphone, Sparkles, Users, Euro, MessageCircle, CalendarCheck } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";

type Client={id:string;name:string;phone:string|null;email:string|null};
type Appointment={client_id:string;starts_at:string;status:string};
type Action={id:string;status:string;target_count:number;contacted_count:number;responded_count:number;booked_count:number;recovered_revenue:number};

export function CeoActionCenter(){
  const [clients,setClients]=useState<Client[]>([]); const [appointments,setAppointments]=useState<Appointment[]>([]); const [prepared,setPrepared]=useState(false); const [copied,setCopied]=useState(false); const [action,setAction]=useState<Action|null>(null);
  useEffect(()=>{let active=true;void Promise.all([supabase.from("clients").select("id,name,phone,email"),supabase.from("appointments").select("client_id,starts_at,status"),(supabase as any).from("ceo_actions").select("id,status,target_count,contacted_count,responded_count,booked_count,recovered_revenue").eq("action_type","client_reactivation").order("created_at",{ascending:false}).limit(1).maybeSingle()]).then(([c,a,x])=>{if(!active)return;if(!c.error)setClients((c.data??[]) as Client[]);if(!a.error)setAppointments((a.data??[]) as Appointment[]);if(!x?.error&&x?.data)setAction(x.data as Action)});return()=>{active=false}},[]);
  const inactive=useMemo(()=>{const now=Date.now(),limit=60*86400000,last=new Map<string,number>();for(const a of appointments){if(a.status==="cancelled")continue;const t=new Date(a.starts_at).getTime();if(t<now)last.set(a.client_id,Math.max(last.get(a.client_id)??0,t))}return clients.filter(c=>{const t=last.get(c.id);return !!t&&now-t>limit})},[clients,appointments]);
  const contactable=inactive.filter(c=>c.phone||c.email); const message="Olá! Já faz algum tempo desde a sua última visita. Temos horários disponíveis e gostaríamos de saber se quer marcar o seu próximo atendimento. Se quiser, responda a esta mensagem e ajudamos a encontrar o melhor horário para si.";
  async function copy(){await navigator.clipboard.writeText(message);setCopied(true);window.setTimeout(()=>setCopied(false),1400)}
  async function startTracking(){setPrepared(true);try{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const payload={user_id:user.id,action_type:"client_reactivation",title:"Recuperar clientes inativos",status:"prepared",target_count:contactable.length,metadata:{client_ids:contactable.map(c=>c.id),message}};const {data,error}=await (supabase as any).from("ceo_actions").insert(payload).select("id,status,target_count,contacted_count,responded_count,booked_count,recovered_revenue").single();if(!error&&data)setAction(data as Action)}catch{}}
  async function updateAction(patch:Partial<Action>){if(!action)return;const next={...action,...patch};setAction(next);try{await (supabase as any).from("ceo_actions").update({...patch,updated_at:new Date().toISOString()}).eq("id",action.id)}catch{}}
  return <section className="mt-5 panel p-5 lg:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><Sparkles className="size-5"/></span><div><p className="eyebrow">CEO AI · Ações com aprovação</p><h2 className="mt-1 text-xl font-bold">Recuperar clientes inativos</h2><p className="mt-1 text-sm text-muted-foreground">O CEO AI encontra o público, prepara a ação e mede o resultado. Nada é enviado automaticamente.</p></div></div><span className="rounded-full border px-3 py-1.5 text-xs font-semibold">{contactable.length} contactos elegíveis</span></div>
  {action&&<div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Stat icon={Users} label="Alvo" value={String(action.target_count)}/><Stat icon={Megaphone} label="Contactados" value={String(action.contacted_count)}/><Stat icon={MessageCircle} label="Responderam" value={String(action.responded_count)}/><Stat icon={CalendarCheck} label="Agendaram" value={String(action.booked_count)}/><Stat icon={Euro} label="Receita recuperada" value={`${Number(action.recovered_revenue||0).toFixed(0)} €`}/></div>}
  {!prepared?<div className="mt-5 rounded-2xl border bg-muted/20 p-5"><div className="grid gap-3 sm:grid-cols-3"><Stat icon={Users} label="Clientes inativos" value={String(inactive.length)}/><Stat icon={Megaphone} label="Com contacto" value={String(contactable.length)}/><Stat icon={CheckCircle2} label="Envio automático" value="Desligado"/></div><button disabled={contactable.length===0} onClick={()=>void startTracking()} className="mt-4 rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground disabled:opacity-50">Preparar campanha de recuperação</button></div>:<div className="mt-5 grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-2xl border bg-muted/20 p-4"><p className="text-sm font-semibold">Público preparado</p><p className="mt-1 text-xs text-muted-foreground">Primeiros clientes identificados pelo histórico da agenda.</p><div className="mt-3 grid gap-2">{contactable.slice(0,6).map(c=><div key={c.id} className="rounded-xl border bg-background px-3 py-2"><p className="text-sm font-semibold">{c.name}</p><p className="text-xs text-muted-foreground">{c.phone??c.email}</p></div>)}</div>{contactable.length>6&&<p className="mt-2 text-xs text-muted-foreground">+ {contactable.length-6} outros contactos</p>}</div><div className="rounded-2xl border bg-background p-4"><p className="text-sm font-semibold">Mensagem sugerida</p><p className="mt-3 rounded-xl bg-muted/30 p-4 text-sm leading-relaxed">{message}</p><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>void copy()} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-sm font-semibold"><Clipboard className="size-4"/>{copied?"Copiado":"Copiar mensagem"}</button>{action&&<><button onClick={()=>void updateAction({contacted_count:Math.min(action.target_count,action.contacted_count+1),status:"contacted"})} className="rounded-xl border px-4 py-2 text-sm font-semibold">+ Contactado</button><button onClick={()=>void updateAction({responded_count:action.responded_count+1,status:"responded"})} className="rounded-xl border px-4 py-2 text-sm font-semibold">+ Respondeu</button><button onClick={()=>void updateAction({booked_count:action.booked_count+1,status:"booked"})} className="rounded-xl border px-4 py-2 text-sm font-semibold">+ Agendou</button><button onClick={()=>{const v=Number(prompt("Receita recuperada (€)","0")||0);if(v>=0)void updateAction({recovered_revenue:v,status:"completed"})}} className="rounded-xl bg-primary px-4 py-2 text-sm font-bold text-primary-foreground">Registar receita</button></>}</div><p className="mt-3 text-[11px] text-muted-foreground">Com WhatsApp/email integrados, os eventos poderão ser atualizados automaticamente.</p></div></div>}</section>
}
function Stat({icon:Icon,label,value}:{icon:React.ComponentType<{className?:string}>;label:string;value:string}){return <div className="rounded-xl border bg-background p-4"><Icon className="size-4 text-primary"/><p className="mt-3 text-xs text-muted-foreground">{label}</p><p className="mt-1 text-lg font-bold">{value}</p></div>}
