/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as TermosDeUtilizacaoRouteImport } from './routes/termos-de-utilizacao'
import { Route as AuthenticatedComandoRouteImport } from './routes/_authenticated/comando'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedGestaoRouteImport } from './routes/_authenticated/gestao'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUtilizacaoRoute = TermosDeUtilizacaoRouteImport.update({
  id: '/termos-de-utilizacao',
  path: '/termos-de-utilizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedComandoRoute = AuthenticatedComandoRouteImport.update({
  id: '/comando',
  path: '/comando',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGestaoRoute = AuthenticatedGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/termos-de-utilizacao': typeof TermosDeUtilizacaoRoute
  '/comando': typeof AuthenticatedComandoRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/gestao': typeof AuthenticatedGestaoRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/termos-de-utilizacao': typeof TermosDeUtilizacaoRoute
  '/comando': typeof AuthenticatedComandoRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/gestao': typeof AuthenticatedGestaoRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/termos-de-utilizacao': typeof TermosDeUtilizacaoRoute
  '/_authenticated/comando': typeof AuthenticatedComandoRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/gestao': typeof AuthenticatedGestaoRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/politica-de-privacidade'
    | '/privacidade'
    | '/redefinir-senha'
    | '/termos'
    | '/termos-de-utilizacao'
    | '/comando'
    | '/crm'
    | '/gestao'
    | '/painel'
    | '/planos'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/politica-de-privacidade'
    | '/privacidade'
    | '/redefinir-senha'
    | '/termos'
    | '/termos-de-utilizacao'
    | '/comando'
    | '/crm'
    | '/gestao'
    | '/painel'
    | '/planos'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/politica-de-privacidade'
    | '/privacidade'
    | '/redefinir-senha'
    | '/termos'
    | '/termos-de-utilizacao'
    | '/_authenticated/comando'
    | '/_authenticated/crm'
    | '/_authenticated/gestao'
    | '/_authenticated/painel'
    | '/_authenticated/planos'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  TermosRoute: typeof TermosRoute
  TermosDeUtilizacaoRoute: typeof TermosDeUtilizacaoRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-utilizacao': {
      id: '/termos-de-utilizacao'
      path: '/termos-de-utilizacao'
      fullPath: '/termos-de-utilizacao'
      preLoaderRoute: typeof TermosDeUtilizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/comando': {
      id: '/_authenticated/comando'
      path: '/comando'
      fullPath: '/comando'
      preLoaderRoute: typeof AuthenticatedComandoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestao': {
      id: '/_authenticated/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof AuthenticatedGestaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedComandoRoute: typeof AuthenticatedComandoRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedGestaoRoute: typeof AuthenticatedGestaoRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedComandoRoute: AuthenticatedComandoRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedGestaoRoute: AuthenticatedGestaoRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  TermosRoute: TermosRoute,
  TermosDeUtilizacaoRoute: TermosDeUtilizacaoRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
